routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account

collections:
  /magazine/:
    permalink: /magazine/{slug}/
    filter: tag:magazine
    template: magazine
    posts_per_page: 12

  /:
    permalink: /{slug}/
    template: index
    posts_per_page: 10

  /investigacoes/:
    permalink: /investigacoes/{slug}/
    filter: tag:investigacoes
    template: index

  /politica/:
    permalink: /politica/{slug}/
    filter: tag:politica
    template: index

  /economia/:
    permalink: /economia/{slug}/
    filter: tag:economia
    template: index

  /justica/:
    permalink: /justica/{slug}/
    filter: tag:justica
    template: index

  /internacional/:
    permalink: /internacional/{slug}/
    filter: tag:internacional
    template: index

  /tecnologia/:
    permalink: /tecnologia/{slug}/
    filter: tag:tecnologia
    template: index

  /cultura/:
    permalink: /cultura/{slug}/
    filter: tag:cultura
    template: index

  /sociedade/:
    permalink: /sociedade/{slug}/
    filter: tag:sociedade
    template: index

  /ambiente/:
    permalink: /ambiente/{slug}/
    filter: tag:ambiente
    template: index

  /saude/:
    permalink: /saude/{slug}/
    filter: tag:saude
    template: index

  /educacao/:
    permalink: /educacao/{slug}/
    filter: tag:educacao
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
